
<!-- This is the project specific website template -->
<!-- It can be changed as liked or replaced by other content -->

<?php

$domain=ereg_replace('[^\.]*\.(.*)$','\1',$_SERVER['HTTP_HOST']);
$group_name=ereg_replace('([^\.]*)\..*$','\1',$_SERVER['HTTP_HOST']);
$themeroot='http://r-forge.r-project.org/themes/rforge/';

echo '<?xml version="1.0" encoding="UTF-8"?>';
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en   ">

  <head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title><?php echo $group_name; ?></title>
	<link href="<?php echo $themeroot; ?>styles/estilo1.css" rel="stylesheet" type="text/css" />
  <style type="text/css">
<!--
.black {	color: #000;
}
.wjzh {	color: #0000A0;
}
.TimeNewRoman {
	font-family: Times New Roman, Times, serif;
}
-->
  </style>
  </head>

<body>

<!-- R-Forge Logo -->
<!-- get project title  -->
<!-- own website starts here, the following may be changed as you like -->
<!-- end of project description -->

<h1 align="center"><font color="#008000"><font face="Times New Roman, serif"><font 
style="FONT-SIZE: 20pt" size="4"><span class="black" lang="en-US" xml:lang="en-US"><strong>Welcome to RQTLNetwork!</strong></span></font></font></font></h1>
<h2 class="black"><span class="TimeNewRoman">1. Introduction</span></h2>
<p>RQTLNetwork, a <a href="http://www.r-project.org/">R</a> package, aims to  provide a user-friendly and platform-independent tool to visualize QTL mapping  results generated by QTLNetwork. It works both on the Windows, Linux/<a href="http://www.freebsd.org/">FreeBSD</a> and MacOS platforms.  The GUI is based on available add-on package <a href="http://www.ggobi.org/rgtk2/">RGtk2</a>, via the aid of  another package <a href="http://cran.r-project.org/web/packages/gWidgetsRGtk2/index.html">gWidgetsRGtk2</a>. Functions for visualizing  are developed by package lattice and grid that are distributed with R by default. </p>
<h2>2. Installation</h2>
<h3>2.1 install GTK+</h3>
<p>Because RGtk2 depends on GTK+, you may need  to install GTK+ before install RGtk2. For windows user, you can do this:<br />
  download GTK+ <a href="http://downloads.sourceforge.net/gladewin32/gtk-2.10.11-win32-1.exe?modtime=1175123376&amp;big_mirror=0">here</a> <br />
  Run the resulting file. This is an  automated installer which will help you complete the installation of Gtk2  libraries.<br />
  For Mac OS users, you can do this:<br />
  Download GTK+ <a href="http://r.research.att.com/gtk2-runtime.dmg">here</a>.<br />
  Run the resulting file.<br />
  In Linux, you may or may not upgrade the  GTK libraries depending on your distribution.<br />
  There are more details on RGtk2 at <a href="http://www.ggobi.org/rgtk2">RGtk2’s home page</a>.</p>
<h3>2.2 install R</h3>
<p>Download  R from <a href="http://cran.r-project.org/">CRAN</a> and install it.</p>
<h3>2.3 install the R packages</h3>
<p>The following R packages are needed: RGtk2,  cairoDevice, gWidgets and gWidgetsRGtk2.   Install them in order, as some depend on others.  All can be downloaded from <a href="http://cran.r-project.org/">CRAN</a>.</p>
<h3>2.4 Install RQTLNetwork</h3>
<p>The RQTLNetwork package is freely available <a href="https://r-forge.r-project.org/projects/rqtlnetwork/">here</a>,  you can download and install.  You can  also install it directly within R by command:</p>
<p><em>install.packages(&quot;RQTLNetwork&quot;,repos=&quot;  http://R-Forge.R-project.org&quot;)</em>.</p>
<h2>3. Running
</h2>
<p>Launch RQTLNetwork by command <em>library(RQTLNetwork)</em> within R and restart it by command <em>RQTLNetwork()</em>.</p>
<p>&nbsp;</p>
<p><strong>Download</strong></p>
<p><a href="http://r-forge.r-project.org/projects/rqtlnetwork/">RQTLNetwork</a></p>
<p><a href="RQTLNetwork_Manual.pdf">User Manual</a></p>
<p><a href="data.zip">Example Data</a></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
</body>
</html>
