
<!-- This is the project specific website template -->
<!-- It can be changed as liked or replaced by other content -->

<?php

$domain=ereg_replace('[^\.]*\.(.*)$','\1',$_SERVER['HTTP_HOST']);
$group_name=ereg_replace('([^\.]*)\..*$','\1',$_SERVER['HTTP_HOST']);
$themeroot='http://r-forge.r-project.org/themes/rforge/';

echo '<?xml version="1.0" encoding="UTF-8"?>';
?>
<!DOCTYPE html
	PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en   ">

  <head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title><?php echo $group_name; ?></title>
	<link href="<?php echo $themeroot; ?>styles/estilo1.css" rel="stylesheet" type="text/css" />
  <style type="text/css">
<!--
.black {	color: #000;
}
.wjzh {	color: #0000A0;
}
.TimeNewRoman {
	font-family: Times New Roman, Times, serif;
}
-->
  </style>
  </head>

<body>

<!-- R-Forge Logo -->
<!-- get project title  -->
<!-- own website starts here, the following may be changed as you like -->
<!-- end of project description -->

<p align="center"><font color="#008000"><font face="Times New Roman, serif"><font 
style="FONT-SIZE: 20pt" size="4"><span class="black" lang="en-US" xml:lang="en-US"><strong>Welcome to RQTLNetwork!</strong></span></font></font></font></p>
<h1 class="black"><span class="TimeNewRoman">1. Introduction</span></h1>
<p>RQTLNetwork, a <a href="http://www.r-project.org/">R</a> package, aims to  provide a user-friendly and platform-independent tool to visualize QTL mapping  results generated by QTLNetwork. It works both on the Windows, Linux/<a href="http://www.freebsd.org/">FreeBSD</a> and MacOS platforms.  The GUI is based on available add-on package <a href="http://www.ggobi.org/rgtk2/">RGtk2</a>, via the aid of  another package <a href="http://cran.r-project.org/web/packages/gWidgetsRGtk2/index.html">gWidgetsRGtk2</a>. Functions for visualizing  are developed by package lattice and grid that are distributed with R by default. </p>
<p>&nbsp;</p>

</body>
</html>
